- hosts: web
  become: true
  gather_facts: false

  tasks:
    - name: Install Python3
      raw: sudo yum install -y python3

    - name: Install Docker
      raw: sudo yum install -y docker

    - name: Start Docker
      raw: sudo systemctl start docker

    - name: Enable Docker
      raw: sudo systemctl enable docker

    - name: Add ec2-user to docker group
      raw: sudo usermod -aG docker ec2-user

    - name: Pull Docker image
      raw: docker pull anisiya99/polkadot-app:latest

    - name: Stop old container
      raw: docker stop app || true

    - name: Remove old container
      raw: docker rm app || true

    - name: Run container
      raw: docker run -d -p 3000:80 --name app anisiya99/polkadot-app:latest
      
